project:
  type: website
  output-dir: docs

website:
  title: "Li Zhang Lab"
  site-url: "https://lz245.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Publications
        href: publications.qmd
      - text: CV
        href: cv.qmd
      - text: Lab
        href: lab.qmd
    right:
      - icon: building-columns
        href: https://www.poultry.msstate.edu/people/lz245
      - icon: github
        href: https://github.com/lz245
      - icon: google
        href: https://scholar.google.com/citations?user=PpnVGN4AAAAJ&hl=en

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full